import type { Bathroom } from "../types";

const DAY_MS = 24 * 60 * 60 * 1000;

export const SEED_BATHROOMS: Bathroom[] = [
  {
    id: "seed-1",
    name: "Blue Bottle Coffee",
    address: "1 Rockefeller Plaza, New York, NY",
    code: "4821",
    type: "cafe",
    isADAAccessible: true,
    isFree: false,
    feeAmount: "",
    note: "Ask the barista, it's behind the counter door.",
    latitude: 40.7587,
    longitude: -73.9787,
    submittedBy: "jen_nyc",
    isVerified: true,
    isZohranToilet: false,
    upvoteCount: 42,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now() - 2 * DAY_MS,
    suggestions: [],
  },
  {
    id: "seed-2",
    name: "Bryant Park Public Restroom",
    address: "Bryant Park, New York, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Open until 10pm, attendant on site.",
    latitude: 40.7536,
    longitude: -73.9832,
    submittedBy: "parks_dept",
    isVerified: true,
    isZohranToilet: false,
    upvoteCount: 128,
    rating: 4.8,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now() - 10 * DAY_MS,
    suggestions: [],
  },
  {
    id: "seed-3",
    name: "Shell Gas Station",
    address: "350 W 42nd St, New York, NY",
    code: "9910",
    type: "gasStation",
    isADAAccessible: false,
    isFree: false,
    feeAmount: "$1.00",
    note: "",
    latitude: 40.7577,
    longitude: -73.9925,
    submittedBy: "demo_user",
    isVerified: false,
    isZohranToilet: false,
    upvoteCount: 6,
    rating: 3.2,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now() - 60 * DAY_MS,
    suggestions: [],
  },
  {
    id: "seed-4",
    name: "Whole Foods Market",
    address: "10 Columbus Cir, New York, NY",
    code: "2468",
    type: "store",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Second floor, near the cafe seating.",
    latitude: 40.7685,
    longitude: -73.9822,
    submittedBy: "demo_user",
    isVerified: true,
    isZohranToilet: false,
    upvoteCount: 19,
    rating: 4.1,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now() - 20 * DAY_MS,
    suggestions: [],
  },
];

// The city's own free public restrooms — the 2026 rollout of 17 units
// across all five boroughs. Coordinates were geocoded from the official
// location list (OpenStreetMap/Nominatim; a handful of street-corner
// installations without a fixed address were approximated to the nearest
// intersection, noted per-entry). Backfilled into any deployment via
// ensureZohranToiletsSeeded() in lib/firestoreBathrooms.ts — unlike
// SEED_BATHROOMS above, this runs regardless of whether the bathrooms
// collection is already populated, keyed by these fixed ids so it's safe
// to run repeatedly.
export const ZOHRAN_TOILETS: Bathroom[] = [
  {
    id: "nyc-toilet-bronx-yankee-stadium",
    name: "Yankee Stadium Public Restroom",
    address: "Yankee Stadium, Bronx, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.8295828,
    longitude: -73.9265212,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-bronx-admiral-farragut-playground",
    name: "Admiral Farragut Playground Public Restroom",
    address: "Admiral Farragut Playground, Bronx, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.8429043,
    longitude: -73.8916427,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-bronx-mapes-park",
    name: "Mapes Park Public Restroom",
    address: "Mapes Park, Bronx, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.8472241,
    longitude: -73.8858122,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-bronx-msgr-del-valle-square",
    name: "Monsignor Raul Del Valle Square Public Restroom",
    address: "Monsignor Raul Del Valle Square, Bronx, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.8207673,
    longitude: -73.8907527,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-brooklyn-columbus-park",
    name: "Columbus Park Public Restroom",
    address: "Columbus Park, Brooklyn, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.6936636,
    longitude: -73.9900105,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-brooklyn-milestone-park",
    name: "Milestone Park Public Restroom",
    address: "Milestone Park, Brooklyn, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.6095496,
    longitude: -73.9995116,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-brooklyn-fulton-truxton",
    name: "Fulton St & Truxton St Public Restroom",
    address: "Fulton Street and Truxton Street, Brooklyn, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    // Recalculated by geocoding Fulton St and Truxton St separately and
    // triangulating where their resolved segments meet — more precise than
    // the original single-street approximation.
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.6783,
    longitude: -73.9062,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-brooklyn-avenue-c-plaza",
    name: "Avenue C Plaza Public Restroom",
    address: "Avenue C Plaza (McDonald Ave & Ave C), Kensington, Brooklyn, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.6405,
    longitude: -73.977,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-queens-astoria-blvd-s-31st",
    name: "Astoria Blvd South & 31st St Public Restroom",
    address: "Astoria Boulevard South and 31st Street, Queens, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.7700748,
    longitude: -73.9183532,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-queens-northern-blvd-31st",
    name: "Northern Blvd & 31st St Public Restroom",
    address: "Northern Boulevard and 31st Street, Queens, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.7518385,
    longitude: -73.9333799,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-queens-northern-blvd-54th",
    name: "Northern Blvd & 54th St Public Restroom",
    address: "Northern Boulevard and 54th Street, Queens, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.7528124,
    longitude: -73.9059454,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-queens-34th-ave-64th",
    name: "34th Ave & 64th St Public Restroom",
    address: "34th Avenue and 64th Street, Queens, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    // Recalculated to 64th St's own geocoded centerline in Woodside — the
    // prior estimate fell noticeably off the actual street.
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.747,
    longitude: -73.8996,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-manhattan-cooper-square",
    name: "Cooper Square Public Restroom",
    address: "Cooper Square, Manhattan, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.7281104,
    longitude: -73.9913436,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-manhattan-malcolm-x-plaza",
    name: "Malcolm X Plaza Public Restroom",
    address: "Malcolm X Plaza, Manhattan, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.7985081,
    longitude: -73.9524896,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-manhattan-delancey-suffolk",
    name: "Delancey St & Suffolk St Public Restroom",
    address: "Delancey Street and Suffolk Street, Manhattan, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    // Recalculated using Delancey St's own resolved latitude and Suffolk
    // St's resolved longitude — Suffolk is short enough that its geocoded
    // centerline sits right at the Delancey crossing.
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.7199,
    longitude: -73.9857,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-manhattan-plaza-alianza-dominicana",
    name: "Plaza Alianza Dominicana Public Restroom",
    address: "Plaza Alianza Dominicana, Washington Heights, Manhattan, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    // Pinned to the Alianza Dominicana Cultural Center (530 W 166th St),
    // the plaza's namesake and closest resolvable landmark.
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.8392644,
    longitude: -73.9396018,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-staten-island-north-shore-esplanade",
    name: "North Shore Esplanade Public Restroom",
    address: "North Shore Esplanade, Staten Island, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.647715,
    longitude: -74.0817455,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
];

// London's paid public toilets — a curated set covering all 8 Royal Parks
// plus several other well-known city-centre locations. Coordinates were
// geocoded via OpenStreetMap/Nominatim; a few specific-spot listings within
// a larger park or market (noted per-entry) were approximated from general
// knowledge of the location since free geocoding couldn't resolve the exact
// point. Backfilled into any deployment via ensureSeeded() in
// lib/firestoreBathrooms.ts, keyed by these fixed ids so it's idempotent.
export const LONDON_TOILETS: Bathroom[] = [
  {
    id: "london-toilet-royal-park-hyde-park",
    name: "Hyde Park Public Toilets",
    address: "Hyde Park, London",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: false,
    feeAmount: "20p",
    note: "One of the 8 Royal Parks. Contactless card or phone only; cash is no longer accepted.",
    latitude: 51.5074889,
    longitude: -0.1622074,
    submittedBy: "london_toilets",
    isVerified: true,
    isZohranToilet: false,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "london-toilet-royal-park-regents-park",
    name: "Regent's Park Public Toilets",
    address: "Regent's Park, London",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: false,
    feeAmount: "20p",
    note: "One of the 8 Royal Parks. Contactless card or phone only; cash is no longer accepted.",
    latitude: 51.5301326,
    longitude: -0.1537641,
    submittedBy: "london_toilets",
    isVerified: true,
    isZohranToilet: false,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "london-toilet-royal-park-st-james-park",
    name: "St James's Park Public Toilets",
    address: "St James's Park, London",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: false,
    feeAmount: "20p",
    note: "One of the 8 Royal Parks. Contactless card or phone only; cash is no longer accepted.",
    latitude: 51.5031295,
    longitude: -0.133165,
    submittedBy: "london_toilets",
    isVerified: true,
    isZohranToilet: false,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "london-toilet-royal-park-green-park",
    name: "Green Park Public Toilets",
    address: "Green Park, London",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: false,
    feeAmount: "20p",
    // Approximated to the park's own centre — free geocoding resolved
    // "Green Park" to the Tube station entrance instead.
    note: "One of the 8 Royal Parks. Contactless card or phone only; cash is no longer accepted.",
    latitude: 51.5049,
    longitude: -0.1441,
    submittedBy: "london_toilets",
    isVerified: true,
    isZohranToilet: false,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "london-toilet-royal-park-kensington-gardens",
    name: "Kensington Gardens Public Toilets",
    address: "Kensington Gardens, London",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: false,
    feeAmount: "20p",
    note: "One of the 8 Royal Parks. Contactless card or phone only; cash is no longer accepted.",
    latitude: 51.5066463,
    longitude: -0.1803888,
    submittedBy: "london_toilets",
    isVerified: true,
    isZohranToilet: false,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "london-toilet-royal-park-richmond-park",
    name: "Richmond Park Public Toilets",
    address: "Richmond Park, London",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: false,
    feeAmount: "20p",
    note: "One of the 8 Royal Parks. Contactless card or phone only; cash is no longer accepted.",
    latitude: 51.4385116,
    longitude: -0.274735,
    submittedBy: "london_toilets",
    isVerified: true,
    isZohranToilet: false,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "london-toilet-royal-park-greenwich-park",
    name: "Greenwich Park Public Toilets",
    address: "Greenwich Park, London",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: false,
    feeAmount: "20p",
    note: "One of the 8 Royal Parks. Contactless card or phone only; cash is no longer accepted.",
    latitude: 51.4772355,
    longitude: 0.0009227,
    submittedBy: "london_toilets",
    isVerified: true,
    isZohranToilet: false,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "london-toilet-royal-park-bushy-park",
    name: "Bushy Park Public Toilets",
    address: "Bushy Park, London",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: false,
    feeAmount: "20p",
    note: "One of the 8 Royal Parks. Contactless card or phone only; cash is no longer accepted.",
    latitude: 51.4168367,
    longitude: -0.3370263,
    submittedBy: "london_toilets",
    isVerified: true,
    isZohranToilet: false,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "london-toilet-camden-market-stables-hawley-wharf",
    name: "Camden Market, Stables Market & Hawley Wharf Public Toilets",
    address: "Stables Market, Camden, London",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: false,
    feeAmount: "Up to £1",
    note: "Hawley Wharf has a Changing Places toilet.",
    latitude: 51.5426473,
    longitude: -0.1476583,
    submittedBy: "london_toilets",
    isVerified: true,
    isZohranToilet: false,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "london-toilet-camden-lock-market",
    name: "Camden Lock Market Public Toilets",
    address: "Camden Lock Market, London",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: false,
    feeAmount: "40p",
    note: "Standalone, accessible.",
    latitude: 51.5412627,
    longitude: -0.1461922,
    submittedBy: "london_toilets",
    isVerified: true,
    isZohranToilet: false,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "london-toilet-victoria-embankment-gardens",
    name: "Victoria Embankment Gardens Public Toilets",
    address: "Victoria Embankment Gardens, Villiers Street, London",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: false,
    feeAmount: "£1",
    note: "Daily 7am–8.30pm. Accessible toilet on a RADAR key.",
    latitude: 51.5086429,
    longitude: -0.1214183,
    submittedBy: "london_toilets",
    isVerified: true,
    isZohranToilet: false,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "london-toilet-piccadilly-circus-station",
    name: "Piccadilly Circus Station Public Toilets",
    address: "Piccadilly Circus Underground Station, London",
    code: "",
    type: "publicRestroom",
    isADAAccessible: false,
    isFree: false,
    feeAmount: "£1",
    note: "7am–11pm Monday to Saturday, 10am–8pm Sunday.",
    latitude: 51.5101383,
    longitude: -0.133936,
    submittedBy: "london_toilets",
    isVerified: true,
    isZohranToilet: false,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "london-toilet-cutty-sark-gardens",
    name: "Cutty Sark Gardens Public Toilets",
    address: "Cutty Sark Gardens, Greenwich, London",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: false,
    feeAmount: "50p",
    // Recalculated from the Cutty Sark ship itself, now precisely geocoded
    // (the plaza's namesake and immediate surroundings) — confirms the
    // prior general-knowledge estimate was already very close.
    note: "Free for RADAR key holders.",
    latitude: 51.482933,
    longitude: -0.0096145,
    submittedBy: "london_toilets",
    isVerified: true,
    isZohranToilet: false,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "london-toilet-greenwich-park-lower-avenue",
    name: "Greenwich Park (Lower Avenue) Public Toilets",
    address: "Lower Avenue, Greenwich Park, London",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: false,
    feeAmount: "20p",
    // Approximated to Lower Avenue's path within the park — free geocoding
    // couldn't resolve this specific internal path.
    note: "Seasonal hours.",
    latitude: 51.4751,
    longitude: -0.0007,
    submittedBy: "london_toilets",
    isVerified: true,
    isZohranToilet: false,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "london-toilet-kensington-gardens-flower-walk",
    name: "Kensington Gardens (Flower Walk) Public Toilets",
    address: "Flower Walk, Kensington Gardens, London",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: false,
    feeAmount: "20p",
    // Approximated to the Flower Walk path near the Albert Memorial — free
    // geocoding couldn't resolve this specific internal path.
    note: "Contactless tap only.",
    latitude: 51.5028,
    longitude: -0.177,
    submittedBy: "london_toilets",
    isVerified: true,
    isZohranToilet: false,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "london-toilet-trafalgar-square",
    name: "Trafalgar Square Public Toilets",
    address: "Trafalgar Square (west side), London",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: false,
    feeAmount: "20p",
    note: "Daily 10am–8pm. Contactless accepted. Accessible toilet and baby change. West side, at the foot of the central staircase.",
    latitude: 51.5079,
    longitude: -0.1288,
    submittedBy: "london_toilets",
    isVerified: true,
    isZohranToilet: false,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "london-toilet-jubilee-gardens-jubiloo",
    name: "The Jubiloo, Jubilee Gardens",
    address: "Jubilee Gardens, London",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: false,
    feeAmount: "£1",
    // Recalculated: free geocoding now resolves Jubilee Gardens itself
    // (bounding box roughly 51.5034–51.5037, -0.1185 to -0.1180) — the
    // previous estimate's longitude fell well outside the actual gardens.
    // Pinned to the box's west edge, closest to the London Eye side.
    note: "North-west corner of the gardens by the London Eye. Open from 10am daily.",
    latitude: 51.5037,
    longitude: -0.1184,
    submittedBy: "london_toilets",
    isVerified: true,
    isZohranToilet: false,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "london-toilet-parliament-street-westminster",
    name: "Parliament Street Public Toilets",
    address: "Parliament Street, Westminster, London",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: false,
    feeAmount: "£1",
    // Recalculated to Parliament Street's own geocoded southern segment
    // (near Parliament Square/Bridge Street, where exit 6 lets out) — free
    // geocoding still can't resolve the specific station exit itself.
    note: "Exit 6 of Westminster station. Daily 7.30am–8.30pm. Baby change and ambulant cubicles.",
    latitude: 51.5013,
    longitude: -0.1261,
    submittedBy: "london_toilets",
    isVerified: true,
    isZohranToilet: false,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
];
