import type { Bathroom } from "../types";

export const SEED_BATHROOMS: Bathroom[] = [
  {
    id: "seed-1",
    name: "Blue Bottle Coffee",
    address: "1 Rockefeller Plaza, New York, NY",
    code: "4821",
    type: "cafe",
    isADAAccessible: true,
    isFree: false,
    feeAmount: "",
    note: "Ask the barista, it's behind the counter door.",
    latitude: 40.7587,
    longitude: -73.9787,
    submittedBy: "jen_nyc",
    isVerified: true,
    upvoteCount: 42,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
  },
  {
    id: "seed-2",
    name: "Bryant Park Public Restroom",
    address: "Bryant Park, New York, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Open until 10pm, attendant on site.",
    latitude: 40.7536,
    longitude: -73.9832,
    submittedBy: "parks_dept",
    isVerified: true,
    upvoteCount: 128,
    rating: 4.8,
    hasVotedUp: false,
    flagCount: 0,
  },
  {
    id: "seed-3",
    name: "Shell Gas Station",
    address: "350 W 42nd St, New York, NY",
    code: "9910",
    type: "gasStation",
    isADAAccessible: false,
    isFree: false,
    feeAmount: "$1.00",
    note: "",
    latitude: 40.7577,
    longitude: -73.9925,
    submittedBy: "demo_user",
    isVerified: false,
    upvoteCount: 6,
    rating: 3.2,
    hasVotedUp: false,
    flagCount: 0,
  },
  {
    id: "seed-4",
    name: "Whole Foods Market",
    address: "10 Columbus Cir, New York, NY",
    code: "2468",
    type: "store",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Second floor, near the cafe seating.",
    latitude: 40.7685,
    longitude: -73.9822,
    submittedBy: "demo_user",
    isVerified: true,
    upvoteCount: 19,
    rating: 4.1,
    hasVotedUp: false,
    flagCount: 0,
  },
];
