import type { Bathroom } from "../types";

const DAY_MS = 24 * 60 * 60 * 1000;

export const SEED_BATHROOMS: Bathroom[] = [
  {
    id: "seed-1",
    name: "Blue Bottle Coffee",
    address: "1 Rockefeller Plaza, New York, NY",
    code: "4821",
    type: "cafe",
    isADAAccessible: true,
    isFree: false,
    feeAmount: "",
    note: "Ask the barista, it's behind the counter door.",
    latitude: 40.7587,
    longitude: -73.9787,
    submittedBy: "jen_nyc",
    isVerified: true,
    isZohranToilet: false,
    upvoteCount: 42,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now() - 2 * DAY_MS,
    suggestions: [],
  },
  {
    id: "seed-2",
    name: "Bryant Park Public Restroom",
    address: "Bryant Park, New York, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Open until 10pm, attendant on site.",
    latitude: 40.7536,
    longitude: -73.9832,
    submittedBy: "parks_dept",
    isVerified: true,
    isZohranToilet: false,
    upvoteCount: 128,
    rating: 4.8,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now() - 10 * DAY_MS,
    suggestions: [],
  },
  {
    id: "seed-3",
    name: "Shell Gas Station",
    address: "350 W 42nd St, New York, NY",
    code: "9910",
    type: "gasStation",
    isADAAccessible: false,
    isFree: false,
    feeAmount: "$1.00",
    note: "",
    latitude: 40.7577,
    longitude: -73.9925,
    submittedBy: "demo_user",
    isVerified: false,
    isZohranToilet: false,
    upvoteCount: 6,
    rating: 3.2,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now() - 60 * DAY_MS,
    suggestions: [],
  },
  {
    id: "seed-4",
    name: "Whole Foods Market",
    address: "10 Columbus Cir, New York, NY",
    code: "2468",
    type: "store",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Second floor, near the cafe seating.",
    latitude: 40.7685,
    longitude: -73.9822,
    submittedBy: "demo_user",
    isVerified: true,
    isZohranToilet: false,
    upvoteCount: 19,
    rating: 4.1,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now() - 20 * DAY_MS,
    suggestions: [],
  },
];

// The city's own free public restrooms — the 2026 rollout of 17 units
// across all five boroughs. Coordinates were geocoded from the official
// location list (OpenStreetMap/Nominatim; a handful of street-corner
// installations without a fixed address were approximated to the nearest
// intersection, noted per-entry). Backfilled into any deployment via
// ensureZohranToiletsSeeded() in lib/firestoreBathrooms.ts — unlike
// SEED_BATHROOMS above, this runs regardless of whether the bathrooms
// collection is already populated, keyed by these fixed ids so it's safe
// to run repeatedly.
export const ZOHRAN_TOILETS: Bathroom[] = [
  {
    id: "nyc-toilet-bronx-yankee-stadium",
    name: "Yankee Stadium Public Restroom",
    address: "Yankee Stadium, Bronx, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.8295828,
    longitude: -73.9265212,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-bronx-admiral-farragut-playground",
    name: "Admiral Farragut Playground Public Restroom",
    address: "Admiral Farragut Playground, Bronx, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.8429043,
    longitude: -73.8916427,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-bronx-mapes-park",
    name: "Mapes Park Public Restroom",
    address: "Mapes Park, Bronx, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.8472241,
    longitude: -73.8858122,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-bronx-msgr-del-valle-square",
    name: "Monsignor Raul Del Valle Square Public Restroom",
    address: "Monsignor Raul Del Valle Square, Bronx, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.8207673,
    longitude: -73.8907527,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-brooklyn-columbus-park",
    name: "Columbus Park Public Restroom",
    address: "Columbus Park, Brooklyn, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.6936636,
    longitude: -73.9900105,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-brooklyn-milestone-park",
    name: "Milestone Park Public Restroom",
    address: "Milestone Park, Brooklyn, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.6095496,
    longitude: -73.9995116,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-brooklyn-fulton-truxton",
    name: "Fulton St & Truxton St Public Restroom",
    address: "Fulton Street and Truxton Street, Brooklyn, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    // Approximated to Truxton St's own location (Ocean Hill) — this short
    // street's exact meeting point with Fulton St wasn't precisely
    // resolvable via free geocoding; close enough for a bathroom pin.
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.6785342,
    longitude: -73.9065667,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-brooklyn-avenue-c-plaza",
    name: "Avenue C Plaza Public Restroom",
    address: "Avenue C Plaza (McDonald Ave & Ave C), Kensington, Brooklyn, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.6405,
    longitude: -73.977,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-queens-astoria-blvd-s-31st",
    name: "Astoria Blvd South & 31st St Public Restroom",
    address: "Astoria Boulevard South and 31st Street, Queens, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.7700748,
    longitude: -73.9183532,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-queens-northern-blvd-31st",
    name: "Northern Blvd & 31st St Public Restroom",
    address: "Northern Boulevard and 31st Street, Queens, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.7518385,
    longitude: -73.9333799,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-queens-northern-blvd-54th",
    name: "Northern Blvd & 54th St Public Restroom",
    address: "Northern Boulevard and 54th Street, Queens, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.7528124,
    longitude: -73.9059454,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-queens-34th-ave-64th",
    name: "34th Ave & 64th St Public Restroom",
    address: "34th Avenue and 64th Street, Queens, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    // Approximated: nearest resolvable point along 34th Ave close to 64th
    // St's meridian in Woodside; free geocoding couldn't pin the exact node.
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.7519,
    longitude: -73.9025,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-manhattan-cooper-square",
    name: "Cooper Square Public Restroom",
    address: "Cooper Square, Manhattan, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.7281104,
    longitude: -73.9913436,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-manhattan-malcolm-x-plaza",
    name: "Malcolm X Plaza Public Restroom",
    address: "Malcolm X Plaza, Manhattan, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.7985081,
    longitude: -73.9524896,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-manhattan-delancey-suffolk",
    name: "Delancey St & Suffolk St Public Restroom",
    address: "Delancey Street and Suffolk Street, Manhattan, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    // Approximated as the midpoint between the two streets' nearby
    // segments; free geocoding didn't resolve the exact corner node.
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.7182,
    longitude: -73.9857,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-manhattan-plaza-alianza-dominicana",
    name: "Plaza Alianza Dominicana Public Restroom",
    address: "Plaza Alianza Dominicana, Washington Heights, Manhattan, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    // Pinned to the Alianza Dominicana Cultural Center (530 W 166th St),
    // the plaza's namesake and closest resolvable landmark.
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.8392644,
    longitude: -73.9396018,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
  {
    id: "nyc-toilet-staten-island-north-shore-esplanade",
    name: "North Shore Esplanade Public Restroom",
    address: "North Shore Esplanade, Staten Island, NY",
    code: "",
    type: "publicRestroom",
    isADAAccessible: true,
    isFree: true,
    feeAmount: "",
    note: "Free NYC public restroom (2026 citywide rollout). Open daily 7am–10pm, touchless, baby-changing station.",
    latitude: 40.647715,
    longitude: -74.0817455,
    submittedBy: "nyc_dot",
    isVerified: true,
    isZohranToilet: true,
    upvoteCount: 0,
    rating: 4.5,
    hasVotedUp: false,
    flagCount: 0,
    lastConfirmedAt: Date.now(),
    suggestions: [],
  },
];
